-- =============================================================================
-- Database Schema for: Memorial Minutes System
-- Generated by: migrate-filemaker Phase 4
-- Source: FileMaker DDR specs (Memorial_Minutes.fmp12)
-- Target: Oracle Database + APEX
-- =============================================================================

-- =============================================================================
-- LOOKUP TABLES (from FileMaker value lists)
-- =============================================================================

-- From value list: Admin Status
CREATE TABLE admin_statuses (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(100) NOT NULL UNIQUE,
  sort_order  NUMBER DEFAULT 0 NOT NULL
);

INSERT INTO admin_statuses (name, sort_order) VALUES
('Committee Formation in Progress', 1),
('MM in Progress', 2),
('ON HOLD', 3),
('MM Submitted/Under Review', 4),
('Photo Needed', 5),
('Alternative MM', 6),
('Admin Wrap Up Needed', 7),
('COMPLETED', 8);

-- From value list: Committee Member Status
CREATE TABLE member_statuses (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(50) NOT NULL UNIQUE,
  sort_order  NUMBER DEFAULT 0 NOT NULL
);

INSERT INTO member_statuses (name, sort_order) VALUES
('Accept', 1),
('Deny', 2),
('No Response', 3),
('Former Chair', 4),
('Former Member', 5);

-- From value list: Committee Member Role
CREATE TABLE member_roles (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(50) NOT NULL UNIQUE,
  sort_order  NUMBER DEFAULT 0 NOT NULL
);

INSERT INTO member_roles (name, sort_order) VALUES
('Chair', 1),
('Co-Chair', 2),
('Member', 3);

-- =============================================================================
-- CORE TABLES (ordered by dependency)
-- =============================================================================

-- Source: FM table "Email_Templates" (4 records, 7 schema fields)
CREATE TABLE email_templates (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject              VARCHAR2(500),
  body                 CLOB,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by           VARCHAR2(100),
  modified_by          VARCHAR2(100)
);

-- Source: FM table "Administration" (360 records, 31 schema fields)
CREATE TABLE memorial_minutes (
  id                                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fm_id                                VARCHAR2(50) UNIQUE NOT NULL, -- Original FM UUID for migration tracking
  first_name                           VARCHAR2(100),
  middle_name                          VARCHAR2(100),
  last_name                            VARCHAR2(100),
  degrees                              VARCHAR2(200),
  date_of_death                        DATE,
  date_informed                        DATE,
  informed_by                          VARCHAR2(200),
  next_of_kin                          VARCHAR2(500),
  huid                                 VARCHAR2(20),
  hms_academic_title                   VARCHAR2(200),
  status_id                            NUMBER REFERENCES admin_statuses(id),
  administration_comments              CLOB,
  hms_institution                      VARCHAR2(200),
  internal_ofa_announcement_date       DATE,
  hms_half_staff_announcement_date     DATE,
  qualifies_for_fom_reading            CHAR(1) CHECK (qualifies_for_fom_reading IN ('Y', 'N')),
  fom_reading_date                     DATE,
  current_dept_head_name               VARCHAR2(200),
  current_dept_head_email              VARCHAR2(200),
  current_dept_head_admin_email        VARCHAR2(200),
  dept_head_outreach_date              DATE,
  name_of_mm_chair                     VARCHAR2(200),
  mm_accepted_date                     DATE,
  mm_photo_obtained                    CHAR(1) CHECK (mm_photo_obtained IN ('Y', 'N')),
  mm_posted_to_ofa_website_date        DATE,
  mm_chair_photo_file_name             VARCHAR2(500), -- Container field becomes file reference
  committee_membership_comments        CLOB,
  committee_milestone_comments         CLOB,
  milestone_guidelines_sent            CHAR(1) CHECK (milestone_guidelines_sent IN ('Y', 'N')),
  milestone_3_mos_status_req_sent      CHAR(1) CHECK (milestone_3_mos_status_req_sent IN ('Y', 'N')),
  milestone_6_mos_status_req_sent      CHAR(1) CHECK (milestone_6_mos_status_req_sent IN ('Y', 'N')),
  milestone_9_mos_status_req_sent      CHAR(1) CHECK (milestone_9_mos_status_req_sent IN ('Y', 'N')),
  milestone_draft_mm_received_date     DATE,
  milestone_cmte_members_thanked_date  DATE,
  milestone_final_accepted_date        DATE,
  created_at                           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at                           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by                           VARCHAR2(100),
  modified_by                          VARCHAR2(100)
);

-- Source: FM table "Cmte_Membership" (1606 records, 14 schema fields)
CREATE TABLE committee_members (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fm_id                 VARCHAR2(50) UNIQUE NOT NULL, -- Original FM UUID
  memorial_minute_id    NUMBER NOT NULL REFERENCES memorial_minutes(id) ON DELETE CASCADE,
  first_name           VARCHAR2(100),
  middle_initial       VARCHAR2(10),
  last_name            VARCHAR2(100),
  degrees              VARCHAR2(200),
  status_id            NUMBER REFERENCES member_statuses(id),
  academic_title       VARCHAR2(200),
  email_address        VARCHAR2(200),
  mailing_address      CLOB,
  committee_role_id    NUMBER REFERENCES member_roles(id),
  membership_comments  CLOB,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by           VARCHAR2(100),
  modified_by          VARCHAR2(100)
);

-- Source: FM table "Cmte_Milestones" (1656 records, 4 schema fields)
CREATE TABLE milestones (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fm_id                 VARCHAR2(50) UNIQUE NOT NULL, -- Original FM UUID
  memorial_minute_id    NUMBER NOT NULL REFERENCES memorial_minutes(id) ON DELETE CASCADE,
  milestone            VARCHAR2(200),
  milestone_date       DATE,
  note                 CLOB,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by           VARCHAR2(100),
  modified_by          VARCHAR2(100)
);

-- Source: FM table "Cmte_Correspondence" (3 records, 7 schema fields)
CREATE TABLE correspondence (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fm_id                 VARCHAR2(50) UNIQUE NOT NULL, -- Original FM UUID
  committee_member_id   NUMBER REFERENCES committee_members(id) ON DELETE SET NULL,
  memorial_minute_id    NUMBER NOT NULL REFERENCES memorial_minutes(id) ON DELETE CASCADE,
  subject              VARCHAR2(500),
  date_sent            DATE,
  decision             VARCHAR2(50) CHECK (decision IN ('Accept', 'Decline')),
  note                 CLOB,
  document_file_name   VARCHAR2(500), -- Container field becomes file reference
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by           VARCHAR2(100),
  modified_by          VARCHAR2(100)
);

-- Source: FM table "Cmte_Reference_Documents" (103 records, 6 schema fields)
CREATE TABLE reference_documents (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fm_id                 VARCHAR2(50) UNIQUE NOT NULL, -- Original FM UUID
  memorial_minute_id    NUMBER NOT NULL REFERENCES memorial_minutes(id) ON DELETE CASCADE,
  document_title       VARCHAR2(500),
  date_received        DATE,
  document_file_name   VARCHAR2(500), -- Container field becomes file reference
  document_comment     CLOB,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by           VARCHAR2(100),
  modified_by          VARCHAR2(100)
);

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Foreign key indexes (essential for performance)
CREATE INDEX idx_memorial_minutes_status ON memorial_minutes(status_id);
CREATE INDEX idx_committee_members_memorial ON committee_members(memorial_minute_id);
CREATE INDEX idx_committee_members_status ON committee_members(status_id);
CREATE INDEX idx_committee_members_role ON committee_members(committee_role_id);
CREATE INDEX idx_milestones_memorial ON milestones(memorial_minute_id);
CREATE INDEX idx_correspondence_member ON correspondence(committee_member_id);
CREATE INDEX idx_correspondence_memorial ON correspondence(memorial_minute_id);
CREATE INDEX idx_reference_docs_memorial ON reference_documents(memorial_minute_id);

-- Search and filter indexes (based on likely APEX searches)
CREATE INDEX idx_memorial_minutes_last_name ON memorial_minutes(last_name);
CREATE INDEX idx_memorial_minutes_death_date ON memorial_minutes(date_of_death);
CREATE INDEX idx_memorial_minutes_huid ON memorial_minutes(huid);
CREATE INDEX idx_committee_members_last_name ON committee_members(last_name);
CREATE INDEX idx_committee_members_email ON committee_members(email_address);
CREATE INDEX idx_milestones_date ON milestones(milestone_date);
CREATE INDEX idx_correspondence_date_sent ON correspondence(date_sent);
CREATE INDEX idx_reference_docs_title ON reference_documents(document_title);

-- Text search indexes for APEX search functionality
CREATE INDEX idx_memorial_minutes_fm_id ON memorial_minutes(fm_id);
CREATE INDEX idx_committee_members_fm_id ON committee_members(fm_id);
CREATE INDEX idx_milestones_fm_id ON milestones(fm_id);
CREATE INDEX idx_correspondence_fm_id ON correspondence(fm_id);
CREATE INDEX idx_reference_docs_fm_id ON reference_documents(fm_id);

-- =============================================================================
-- TRIGGERS (for updated_at automatic maintenance)
-- =============================================================================

-- Create trigger function for updating modified timestamp
CREATE OR REPLACE TRIGGER trg_email_templates_updated_at
  BEFORE UPDATE ON email_templates
  FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_memorial_minutes_updated_at
  BEFORE UPDATE ON memorial_minutes
  FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_committee_members_updated_at
  BEFORE UPDATE ON committee_members
  FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_milestones_updated_at
  BEFORE UPDATE ON milestones
  FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_correspondence_updated_at
  BEFORE UPDATE ON correspondence
  FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_reference_documents_updated_at
  BEFORE UPDATE ON reference_documents
  FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- =============================================================================
-- VIEWS (for computed/calculated fields)
-- =============================================================================

-- Memorial Minutes with formatted name (replaces FM calculated field)
CREATE OR REPLACE VIEW v_memorial_minutes_with_names AS
SELECT
  mm.*,
  CASE
    WHEN middle_name IS NOT NULL THEN
      first_name || ' ' || middle_name || ' ' || last_name
    ELSE
      first_name || ' ' || last_name
  END AS full_name,
  status.name as status_name
FROM memorial_minutes mm
LEFT JOIN admin_statuses status ON mm.status_id = status.id;

-- Committee members with formatted name and status
CREATE OR REPLACE VIEW v_committee_members_with_names AS
SELECT
  cm.*,
  CASE
    WHEN middle_initial IS NOT NULL THEN
      first_name || ' ' || middle_initial || ' ' || last_name
    ELSE
      first_name || ' ' || last_name
  END AS full_name,
  ms.name as status_name,
  mr.name as role_name,
  -- Is Chair calculation (replaces FM calculated field)
  CASE
    WHEN mr.name = 'Chair' AND ms.name = 'Accept' THEN 1
    ELSE 0
  END as is_chair
FROM committee_members cm
LEFT JOIN member_statuses ms ON cm.status_id = ms.id
LEFT JOIN member_roles mr ON cm.committee_role_id = mr.id;

-- Committee chair view (replaces complex FM relationship)
CREATE OR REPLACE VIEW v_committee_chairs AS
SELECT
  memorial_minute_id,
  full_name as chair_name,
  email_address as chair_email
FROM v_committee_members_with_names
WHERE is_chair = 1;

-- =============================================================================
-- SEQUENCES (for APEX use if needed)
-- =============================================================================

-- Oracle APEX may need explicit sequences for some operations
-- These are created automatically with IDENTITY columns, but listed here for reference:
-- CREATE SEQUENCE seq_memorial_minutes START WITH 1000;
-- CREATE SEQUENCE seq_committee_members START WITH 1000;
-- CREATE SEQUENCE seq_milestones START WITH 1000;
-- CREATE SEQUENCE seq_correspondence START WITH 1000;
-- CREATE SEQUENCE seq_reference_documents START WITH 1000;

-- =============================================================================
-- NOTES
-- =============================================================================

-- Globals-only tables (not migrated as database tables):
-- - g_Membership Filter: Application state - implement as APEX page item or session state

-- Calculated fields (implemented as views or application logic):
-- - Administration.Name: Full name concatenation (see v_memorial_minutes_with_names)
-- - Administration.Constant: Static value 1 (used for relationships - not needed in SQL)
-- - Cmte_Membership.Is_Chair: Chair status calculation (see v_committee_members_with_names)
-- - Cmte_Membership.Name: Full name concatenation (see v_committee_members_with_names)

-- Container fields (converted to file references):
-- - Administration.MM Chair Photo → mm_chair_photo_file_name (store APEX file reference)
-- - Cmte_Correspondence.Document → document_file_name (store APEX file reference)
-- - Cmte_Reference_Documents.Document → document_file_name (store APEX file reference)

-- Data migration notes:
-- - fm_id columns preserve original FileMaker UUIDs for migration validation
-- - All dates should be imported in YYYY-MM-DD format
-- - Container files need to be exported from FM and uploaded to APEX file storage
-- - Status text values should be mapped to lookup table IDs during import
-- - Original creation/modification timestamps and users preserved in audit fields

-- APEX implementation notes:
-- - Use views (v_*) for APEX interactive reports to get calculated fields
-- - APEX file upload regions for container field replacements
-- - APEX LOV (List of Values) based on lookup tables for dropdowns
-- - Row-level security not needed (no record-level restrictions in original FM solution)